### ISSUE TITLE
Rain droplets don't stop when game is paused

### ISSUE THREAD

**Issue by AeroWidescreen** [ThirteenAG/XboxRainDroplets#1]
I noticed that the animation does not stop when the game is paused. Would this be possible to fix? Carbon has an address (00A8AD18) that you could use for this.

Amazing mod btw. I didn't realize this existed for Carbon until now.

**Comment by ThirteenAG** [comment]
Yeah, I just didn't implement it, it needs a timestep address, like so:
https://github.com/aap/skygfx_vc/blob/master/src/neoWaterdrops.cpp#L862
I maybe will add it later.

**Comment by ThirteenAG** [comment]
Okay, added. I also need to port it to MW, pretty sure everything should work identically there.
In NFSU2 couldn't find how to check for rain, other than to use forced rain and check for that.
And no idea if NFSU1 even has rain.

**Comment by AeroWidescreen** [comment]
Nice, but I noticed that in Carbon the rain does not disappear when I go back to the frontend. This problem does not exist in Most Wanted based on my testing.

![carbon](https://i.imgur.com/o8WxCFD.jpg)

> And no idea if NFSU1 even has rain.

It doesn't.

**Comment by ThirteenAG** [comment]
Should be fixed now.

**Comment by AeroWidescreen** [comment]
Confirmed, thanks.
