### ISSUE TITLE
[Max Payne 3] Only works on dx9

### ISSUE THREAD

**Issue by ZT-1** [ThirteenAG/XboxRainDroplets#13]
RainDroplets currently only works on dx9 and isn't functional on dx11.

dx9
![20230913182619_1](https://github.com/ThirteenAG/XboxRainDroplets/assets/11493450/bf3690de-d1fa-4b82-8077-ad83225677a3)

dx11
![20230913182454_1](https://github.com/ThirteenAG/XboxRainDroplets/assets/11493450/d834ecb7-8a8f-4523-b662-849549e6fb10)

**Comment by ThirteenAG** [comment]
Have you switched to dx11 on the fly? I think it might need a full restart before they appear on 11.

**Comment by ZT-1** [comment]
MP3 always requires a full restart when you change directx versions so this was always after restarting.

**Comment by ZT-1** [comment]
With this, it doesn't work on dx11 or 9. But on the git releases one, it works only on dx9.

**Comment by ThirteenAG** [comment]
Apparently it was case sensitivity thing, I hooked d3d11.dll, but the game was loading D3D11.dll. Try the latest version on github.

**Comment by ZT-1** [comment]
Seems to be working now on both dx11 and 9, haven't noticed any other issues. Thank you tag. (Screen is on dx11).
![20231005203721_1](https://github.com/ThirteenAG/XboxRainDroplets/assets/11493450/9dca2157-c603-4ccd-961e-1806e9cd6e67)

**Comment by ThirteenAG** [comment]
Np, thank you for noticing, somehow it was working when I tested.
