### ISSUE TITLE
[Bug Report] Having XboxRainDroplets in the Plugins folder crashes the game on launch.

### ISSUE THREAD

**Issue by Shockwave508** [ThirteenAG/XboxRainDroplets#16]
As of the newest version of Max Payne 3's FusionFix, having the XboxRainDroplets plugin inside the Plugins folder will cause the game to crash immediately after signing in to Rockstar Launcher. 

Perhaps XRD needs updating to the newer codebase?

**Comment by ThirteenAG** [comment]
Try the new build released on github,

**Comment by Shockwave508** [comment]
Can confirm it boots up without issues now!
