### ISSUE TITLE
NFS Underground 2 mod not working

### ISSUE THREAD

**Issue by NBA2K1** [ThirteenAG/XboxRainDroplets#17]
I have, as stated in the releases, first installed the latest Widescreen Fix, which works perfectly BTW, and then put the two files from this mod into the scripts folder.
When I want to start the game, I get an error message with the title "ASI Loader" saying: Unable to load NFSUnderground2.XboxRainDroplets.asi. Error: 126

When I click on OK, the game just starts normally but the mod is not working.

I tried to delete the NFSU2ExtraOptions mod to exclude that it isn't causing that error but it didn't help.

![Screenshot 2024-01-16 234623](https://github.com/ThirteenAG/XboxRainDroplets/assets/78034913/d94fdc00-e680-4cde-891a-28dca0cff702)

**Comment by ThirteenAG** [comment]
You need to install https://www.microsoft.com/en-us/Download/confirmation.aspx?id=35
