### ISSUE TITLE
Weird Flash (NFSU2 Ver.)

### ISSUE THREAD

**Issue by TBNRassault0030** [ThirteenAG/XboxRainDroplets#9]
![Screenshot (521)](https://user-images.githubusercontent.com/86336214/198867820-3a6f80ee-7507-4eb0-a790-aa284c6591d4.png)
![Screenshot (522)](https://user-images.githubusercontent.com/86336214/198867822-3622a916-b2f3-4103-8bb6-af356f843ef2.png)

This thing happens every I go from safehouse to explore mode for the first time every time I boot the game.

**Comment by TBNRassault0030** [comment]
P.S.: I didn't use also any shaders that requires NFS ReShade by Xanvier. I just have it for non-shader settings.

**Comment by TBNRassault0030** [comment]
![Screenshot (528)](https://user-images.githubusercontent.com/86336214/198870882-a251aac9-c2a4-429e-91bf-d84d562b7ce8.png)
![Screenshot (529)](https://user-images.githubusercontent.com/86336214/198870884-09ef4e64-2e1c-4a18-9899-6fbff3a09862.png)

BTW, Why did I just think of this just now, I just remove the NFS ReShade Files out of game directory, I though ReShade was making this thing, but it isn't.

**Comment by xan1242** [comment]
I can't replicate. 

Whatever else you're using, e.g. ExOpts' Force Rain, is breaking the fog rendering.

You're also using HD Reflections by @AeroWidescren

Whatever it is, this does not appear to be an issue with this plugin, but something else.
